### ISSUE TITLE
No Project file?

### ISSUE THREAD

**Issue by TheOnlyRealTodd** [shad0wk/winmod#1]
Hey @shad0wk where's the project file for this? Also, when you're ready for me to contribute, you can add me on this repo. I just deleted my fork lol.

This is "Tee See" btw.

**Comment by shad0wk** [comment]
Oh, yeah there's no project file because I'm not using Visual Studio, I'm using Notepad++ and csc.exe (Visual C# Compiler). Yep you should be added.
